K: 0.1
batch_size: 195
dropout: 0.0
hidden_size: 244
init_points: 40
linear_size: 85
loss: mse
lr: 0.00049338621009839
name: /home/grandovecu/rnn_autoregression_model/logs/overfitting_K=0.1
num_lin_layers: 1
num_rnn_layers: 2
optimizer: adam
precision: 32-true
sampling: random
seq_length: 28
sequence_type: many-to-one
shuffle_batches: false
shuffle_sequences: false
shuffle_trajectories: true
steps: 45
