sim:
    N: 8
    timesteps: 1000
    dt: 0.1
    alpha: 0.5
    beta: 0.0

model:
    hidden_units: 30
    window_size: 50
    step_size: 1
    num_layers: 1
    train_size: 0.8
    val_size: 0.2
    dropout: 0.1

train:
    epochs: 20
    batch_size: 100
    loss: "mse"
    learn_rate: 0.01

hyper_par: {
    "init_points": [5, 30, 80],
    "steps": [600, 1000, 1500],
    "hidden_units": [30, 60, 100],
    "window_size": [50, 100, 299],
    "step_size": [1],
    "num_layers": [1, 2, 5],
    "epochs": [2],
    "batch_size": [100],
    "learn_rate": [0.01],
    "dropout": [0.01],
    "model": ["RNN", "GRU"],
    }