stdm_parameters:
    init_points: 10
    steps: 200
    K: 0.2
    sampling: normal

model_parameters:
    hidden_units: 10
    num_layers: 2
    dropout: 0.0

machine_learning_parameters:
    window_size: 50
    step_size: 1
    train_size: 0.8
    epochs: 10
    batch_size: 200
    loss: mse
    learn_rate: 0.01

parameter_tuning: {
    init_points: [5, 10, 30],
    steps: [600, 800],
    hidden_units: [40, 70, 100],
    window_size: [300, 400],
    step_size: [1],
    num_layers: [3, 4, 5],
    epochs: [200],
    batch_size: [200, 250],
    learn_rate: [0.001, 0.003],
    dropout: [0.001, 0.005, 0.0005],
}