{
  K: 0.1,
  batch_size: 500,
  dropout: 0.0,
  hidden_size: 20,
  init_points: 40,
  linear_size: 20,
  loss: mse,
  lr: 0.0015125081862421542,
  name: logs/overfitting_K=0.1,
  num_lin_layers: 2,
  num_rnn_layers: 2,
  optimizer: adam,
  precision: 32-true,
  sampling: random,
  seq_length: 29,
  sequence_type: many-to-one,
  shuffle_batches: false,
  shuffle_sequences: false,
  shuffle_trajectories: true,
  steps: 45,
}
