{K: 0.1, batch_size: 232, dropout: 0.0, hidden_size: 101, init_points: 40, linear_size: 47,
  loss: mse, lr: 0.0013587445384899135, name: logs/overfitting_K=0.1, num_lin_layers: 2,
  num_rnn_layers: 2, optimizer: adam, precision: 32-true, sampling: random, seq_length: 25,
  sequence_type: many-to-one, shuffle_batches: false, shuffle_sequences: false, shuffle_trajectories: true,
  steps: 45}
