{K: 0.1, batch_size: 150, dropout: 0.0, hidden_size: 82, init_points: 40, linear_size: 135,
  loss: mse, lr: 0.001066120120597101, name: logs/overfitting_K=0.1, num_lin_layers: 2,
  num_rnn_layers: 4, optimizer: adam, precision: 32-true, sampling: random, seq_length: 23,
  sequence_type: many-to-one, shuffle_batches: false, shuffle_sequences: false, shuffle_trajectories: true,
  steps: 45}
