init_points: 40
steps: 45 # ≤ 100
K: 0.1 # ≤ 1.5
sampling: random

hidden_size: 128
linear_size: 128 # used when num_lin_layers > 1
num_rnn_layers: 2
num_lin_layers: 2
dropout: 0.0 # doesn't seem necessary

batch_size: 256
seq_length: 20
loss: mse
optimizer: adam
lr: 0.0003
precision: 32-true

shuffle_trajectories: True # makes sense for linear sampling
shuffle_batches: False # shuffle batches between epochs
shuffle_sequences: False # shuffle sequences

sequence_type: many-to-one # type of input sequences (many-to-one or many-to-many)

name: logs/overfitting_K=0.1

gridsearch:
  batch_size: { lower: 150, upper: 250, type: int }
  seq_length: { lower: 20, upper: 30, type: int }
  lr: { lower: 0.0004, upper: 0.002, type: float }
  num_rnn_layers: { lower: 1, upper: 5, type: int }
  num_lin_layers: { lower: 1, upper: 5, type: int }
  hidden_size: { lower: 100, upper: 250, type: int }
  linear_size: { lower: 20, upper: 100, type: int }
