init_points: 40
steps: 45 # ≤ 100
K: 0.1 # ≤ 1.5
sampling: random

hidden_size: 32
linear_size: 32 # used when num_lin_layers > 1
num_rnn_layers: 1
num_lin_layers: 1
dropout: 0.0 # doesn't seem necessary

batch_size: 256
seq_length: 5
loss: mse
optimizer: adam
lr: 0.0003
precision: 32-true

shuffle_trajectories: True # makes sense for linear sampling
shuffle_batches: None # shuffle batches between epochs (None necesary for ddp)
shuffle_sequences: False # shuffle sequences

sequence_type: many-to-one # type of input sequences (many-to-one or many-to-many)

name: logs/overfitting_K=0.1

gridsearch:
  batch_size: { lower: 150, upper: 230, type: int }
  seq_length: { lower: 20, upper: 30, type: int }
  lr: { lower: 0.0004, upper: 0.002, type: float }
  precision: { list: [32-true, 64-true], type: choice }
  num_rnn_layers: { lower: 2, upper: 5, type: int }
  hidden_size: { lower: 120, upper: 210, type: int }
  num_lin_layers: { lower: 2, upper: 4, type: int }
  linear_size: { lower: 20, upper: 80, type: int }
