K: 0.1
batch_size: 256
dropout: 0.0
epochs: 20
gridsearch:
  batch_size: {lower: 213, type: int, upper: 222}
  lr: {lower: 0.000531118857461078, type: float, upper: 0.0009393333558087654}
  num_lin_layers: {lower: 1, type: int, upper: 3}
  num_rnn_layers: {lower: 3, type: int, upper: 5}
  precision:
    list: [64-true]
    type: choice
  seq_length: {lower: 24, type: int, upper: 30}
hidden_size: 32
init_points: 40
linear_size: 32
loss: mse
lr: 0.0003
name: logs/overfitting_K=0.6/1
num_lin_layers: 1
num_rnn_layers: 1
optimizer: adam
precision: 32-true
sampling: random
seq_length: 5
sequence_type: many-to-one
shuffle_batches: false
shuffle_paths: true
shuffle_sequences: false
steps: 45
