K: 0.1
batch_size: 201
dropout: 0.0
hidden_size: 172
init_points: 40
linear_size: 147
loss: mse
lr: 0.0013096017444440685
name: /home/grandovecu/rnn_autoregression_model/logs/overfitting_K=0.1
num_lin_layers: 3
num_rnn_layers: 3
optimizer: adam
precision: 32-true
sampling: random
seq_length: 23
sequence_type: many-to-one
shuffle_batches: false
shuffle_sequences: false
shuffle_trajectories: true
steps: 45
