K: 0.1
batch_size: 243
dropout: 0.0
hidden_size: 164
init_points: 40
linear_size: 51
loss: mse
lr: 0.001937393819162509
name: /home/grandovecu/rnn_autoregression_model/logs/overfitting_K=0.1
num_lin_layers: 2
num_rnn_layers: 2
optimizer: adam
precision: 32-true
sampling: random
seq_length: 26
sequence_type: many-to-one
shuffle_batches: false
shuffle_sequences: false
shuffle_trajectories: true
steps: 45
